# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'daily-trivia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for daily-trivia

  target 'daily-triviaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'daily-triviaUITests' do
    # Pods for testing
  end

end
