# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'daily-trivia' do
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  use_modular_headers!
  use_frameworks!
end
